go_library(
    name = "decoding",
    srcs = ["decoding.go"],
    visibility = ["//src/..."],
    deps = [],
)

go_test(
    name = "decoding_test",
    srcs = ["decoding_test.go"],
    deps = [
        ":decoding",
        "//third_party:require",
    ]
)
